## Numerical Python (Numpy)

NumPy is the fundamental package for scientific computing in Python. The main benefit of Numpy is its powerful N-dimensional array object that it provides. An array is collection of items stored at contiguous memory locations. 

The idea is to store multiple items of same type together. https://numpy.org/doc/stable/

### Creating one-dimensional array

In [1]:
#importing the numpy library
import numpy as np

In [2]:
firstlist = [1, 2, 3, 4, 5] #Creating a list
a = np.array(firstlist) # Passing the list as a numpy array using np.array
a

array([1, 2, 3, 4, 5])

In [4]:
#type of list
type(firstlist)

list

In [5]:
#type of a
type(a)

numpy.ndarray

In [21]:
a.ndim #Dimension of the array

1

In [25]:
a.size  #size is used to know the array length

5

### Creating multidimensional array

In [26]:
list_of_lists = np.array ([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
list_of_lists

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
#Using the shape method to find the dimensions of the array (rows, columns)
list_of_lists.shape

(3, 4)

In [28]:
list_of_lists.ndim #dimension of array

2

In [55]:
list_of_lists.size #size is used to know the array length

12

In [56]:
#Using arrange method to return evenly spaced value within a given interval


np.arange(0,20) #Starts from zero and generates 20 numbers. Note it wont include the last digit

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [57]:
ar = np.arange(20) #Numpy will intelligently generate 20 numbers starting from zero and also exclude the last digit
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [58]:
np.arange(0,20,2) #generate 20 numbers from 0 to 20 with an interval of 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [59]:
for i in range(0,20,3):  #using for loop to generate numbers ranging from 0 to 20 with interval of 3
    print(i)

0
3
6
9
12
15
18


In [60]:
zero = np.zeros(10) #returns an array filled with zeros
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [61]:
zero = np.zeros((3,4)) #returns an array with shape (3,4) filled with zeros
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [62]:
np.ones((3,4)) #returns an array of given shape filled with ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [63]:
np.eye(10) #returns 1 along the diagonal 10 times

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [64]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [65]:
len(ar) #length of array

20

In [66]:
#creates a new shape to an array without changing its data N/B:The shape should be equal to the length of the array

new_variable = ar.reshape(5,4)
new_variable

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [67]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [68]:
#returns 10 equally spaced values from 0 to 7. N/B: This will always give decimals comapred to the arange function
b = np.linspace(0,7,10)
b

array([0.        , 0.77777778, 1.55555556, 2.33333333, 3.11111111,
       3.88888889, 4.66666667, 5.44444444, 6.22222222, 7.        ])

In [69]:
len(b)

10

In [70]:
b.resize(5,2) #This will create anew shape but alter the data
b

array([[0.        , 0.77777778],
       [1.55555556, 2.33333333],
       [3.11111111, 3.88888889],
       [4.66666667, 5.44444444],
       [6.22222222, 7.        ]])

In [71]:
b

array([[0.        , 0.77777778],
       [1.55555556, 2.33333333],
       [3.11111111, 3.88888889],
       [4.66666667, 5.44444444],
       [6.22222222, 7.        ]])

Difference between resize and reshape is that it will reshape will not ulter the array unlike resize which will ulter the array.

## Generating random values

In [72]:
#Creates an aray with given shape and populate it with random samples.

np.random.rand(5,3)

array([[0.98446302, 0.01784384, 0.92425107],
       [0.9400648 , 0.63509081, 0.38180943],
       [0.682176  , 0.86212197, 0.75691992],
       [0.4418638 , 0.51905563, 0.79312491],
       [0.23117898, 0.46053419, 0.05691184]])

In [75]:
#Return a sample (or samples) from the “standard normal” distribution.
c = np.random.randn(3,3)
c

array([[-1.21655713,  0.29679897,  1.02514975],
       [-1.06337838, -2.07946284,  1.5823705 ],
       [-1.08694163,  0.64464825, -1.28872901]])

In [77]:
#Return 11 random integers from 2 to 50
kk = np.random.randint(2, 50, 11)
kk

array([23,  3, 23,  7, 42, 23, 35,  3, 10, 29, 23])

In [80]:
#return random number from 2 to 50 with shape
kk = np.random.randint(2,50, (5,4))
kk

array([[37,  3,  3, 14],
       [14, 37, 37, 38],
       [26, 37, 49, 26],
       [35, 28, 44, 21],
       [15, 45, 19,  7]])

## Indexing and Slicing

In [82]:
kk = np.random.randint(2,50,11)
kk

array([41,  2, 45, 12,  2,  3, 21, 18, 19, 37, 42])

In [83]:
kk[1] #returns index position of 1. N/B: counting begins from 0 index

2

In [84]:
kk[-1] #returns index position from behind

42

In [85]:
kk[3:7] # selecting item within a range but doesnt include the last number

array([12,  2,  3, 21])

In [96]:
kc = np.arange(50)
kc

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [97]:
kc.resize(10,5)
kc

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [98]:
kc[2,3] #returns index position for rows and columns

13

In [99]:
kc[3, 2:6]

array([17, 18, 19])

In [100]:
kc[2:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [101]:
kc[2:,2:]

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24],
       [27, 28, 29],
       [32, 33, 34],
       [37, 38, 39],
       [42, 43, 44],
       [47, 48, 49]])

In [102]:
kc[kc > 15] #condiitonal formatting

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [104]:
kc[kc > 15] = 20 #casting all the values greater than 15 to 20
kc

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20]])

In [106]:
kc

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20]])

In [107]:
kc[1:, 4]

array([ 9, 14, 20, 20, 20, 20, 20, 20, 20])

In [108]:
kc[3:, 2]

array([20, 20, 20, 20, 20, 20, 20])

## Creating a copy

In [110]:
kc_copy = kc.copy() #This creates a copy of the original data which you can now manipulate rather than the original
kc_copy

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20]])

In [111]:
kc

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20]])

### Broadcasting

In [114]:
kc_copy[kc_copy > 15] = 15
kc_copy

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15]])

In [115]:
kc

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20]])

### Matrix

In [116]:
#Creating a multidimensional array
my_matrix = np.array(([20,4,7,3], [88,9,2,6], [102,57,11,31], [19,99,1,14]))
my_matrix

array([[ 20,   4,   7,   3],
       [ 88,   9,   2,   6],
       [102,  57,  11,  31],
       [ 19,  99,   1,  14]])

In [120]:
#Creating a matrix
matrix = np.matrix([[5,6,7], [3,1,9]])
matrix

matrix([[5, 6, 7],
        [3, 1, 9]])

In [121]:
matrix[1,2]

9

In [122]:
matrix.mean()

5.166666666666667

In [123]:
matrix.std()

2.608745973749755

In [124]:
matrix.var()

6.805555555555556